---
- name: Change the admin shell to advanced
  #/////////////////////////////////////////////////////////////////
  #Created by S. Tariq Ali
  #Created on 20210420
  #This script will perform  following tasks
  #Change the admin shell to advanced
  #/////////////////////////////////////////////////////////////////
  hosts: my_dg

  gather_facts: false
  remote_user: root

  tasks:
    - name: Change the user "admin" role and shell
      no_log: true
      bigip_user:
        username_credential: admin
        partition_access:
          - all:admin
        shell: bash
        state: present
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: false
      register: device_facts
      delegate_to: localhost
